export {
  ApiClient,
  ApiError,
  createApiClient,
  createAuthenticatedApiClient,
  type ApiClientConfig,
  type ApiRequestOptions,
} from './client';
export {
  getOrSwitchSession,
  getProfile,
  logoutSession,
  refreshToken,
  requestOtp,
  toE164IndianMobile,
  updateProfile,
  verifyOtp,
  type OtpChannel,
  type Profile,
  type RequestOtpBody,
  type RequestOtpResult,
  type SessionRoles,
  type TokenPair,
  type VerifyOtpBody,
} from './auth';
export { grantConsent, listConsents, type ConsentItem, type ConsentPurpose } from './consent';
export {
  registerDeviceToken,
  unregisterDeviceToken,
  type DevicePlatform,
  type DeviceRegistered,
  type RegisterDeviceBody,
} from './devices';
export {
  attachQr,
  resolveQr,
  type ConsumerAttachBody,
  type ConsumerAttachQrStatus,
  type ConsumerAttachResult,
  type QrChannel,
  type QrJourney,
  type QrOfferedSku,
  type QrPublicVehicle,
  type QrResolution,
  type QrStatus,
} from './qr';
export { getLegalDocuments, type LegalDocuments } from './legal';
export {
  lookupVehicle,
  listVehicles,
  getVehicleById,
  type RcRecordDto,
  type VehicleDetailDto,
  type VehicleSummaryDto,
} from './vehicles';
export {
  listPlans,
  type ApiPlanTier,
  type ListPlansParams,
  type PlanOptionDto,
  type PlanPeriod,
  type RiderOptionDto,
} from './plans';
export {
  createOrder,
  payOrder,
  getOrderPayment,
  getOrderInvoice,
  type CreateOrderBody,
  type OrderDto,
  type OrderInvoiceDto,
  type OrderStatus,
  type PayOrderBody,
  type PayOrderMode,
  type PaymentOutcome,
  type PaymentOutcomeDto,
  type PaymentRefDto,
} from './orders';
export { createCart, getCart, type CartDto, type CreateCartBody } from './cart';
export { validatePromo, type PromoPreviewDto, type ValidatePromoBody } from './promos';
export {
  previewActivation,
  redeemActivation,
  type ActivationPreviewDto,
  type ActivationPreviewChannel,
  type ActivationPreviewPartner,
  type ActivationRedeemedDto,
  type RedeemActivationBody,
  type RedeemActivationB2b2cBody,
  type RedeemActivationB2bBody,
} from './activation';
export {
  listEmergencyContacts,
  requestEmergencyContactOtp,
  verifyEmergencyContactOtp,
  createEmergencyContact,
  deleteEmergencyContact,
  type EmergencyContactDto,
  type EmergencyContactOtpRequestedDto,
  type EmergencyContactOtpVerifiedDto,
  type EmergencyContactCreatedDto,
  type RequestEmergencyContactOtpBody,
  type VerifyEmergencyContactOtpBody,
  type CreateEmergencyContactBody,
} from './emergency-contacts';
export {
  listSubscriptionRiders,
  requestRiderOtp,
  verifyRiderOtp,
  createRider,
  deleteRider,
  type RiderDto,
  type RiderOtpRequestedDto,
  type RiderOtpVerifiedDto,
  type RiderCreatedDto,
  type RequestRiderOtpBody,
  type VerifyRiderOtpBody,
  type CreateRiderBody,
} from './riders';
export {
  requestParkOtp,
  verifyParkOtp,
  lookupParkVehicle,
  requestParkMediaUpload,
  completeParkMediaUpload,
  openPark,
  getParkStatus,
  requestEmergencyMediaUpload,
  completeEmergencyMediaUpload,
  acceptEmergency,
  cancelEmergencyAlert,
  getEmergencyAlertStatus,
  type ParkOtpRequestBody,
  type ParkOtpRequestedDto,
  type ParkOtpVerifyBody,
  type ParkSessionTokenDto,
  type ParkVehicleLookupBody,
  type BystanderRcRecordDto,
  type RequestScanUploadBody,
  type RequestParkUploadBody,
  type ScanUploadTargetDto,
  type RequestScanUploadResponseDto,
  type CompleteParkUploadBody,
  type ScanMediaCompletedDto,
  type OpenParkBody,
  type ParkOpenedDto,
  type ParkStatus,
  type ParkStatusDto,
  type AcceptEmergencyBody,
  type EmergencyAcceptedDto,
  type AlertStatus,
  type EmergencyDispatchPath,
  type AlertStatusDto,
  type CancelAlertResponseDto,
} from './scanner';
export { normalizeApiError, type NormalizedApiError, type NormalizedErrorCode } from './errors';
export { wireTokenRefresh } from './interceptors';
export {
  unwrapEnvelope,
  readEnvelopeMeta,
  type ApiEnvelope,
  type ApiErrorEnvelope,
} from './envelope';
export { endpoints, type EndpointGroup } from './endpoints';
export {
  createAdminPromo,
  createQrBatch,
  findAdminUserByPhone,
  generateQrBatchCodes,
  getAdminOrder,
  grantUserRole,
  revokeUserRole,
  listAdminOrdersPage,
  listAdminPromos,
  listQrInventory,
  listQrBatchCodes,
  listQrBatchCodesPage,
  exportQrBatchCodesCsv,
  listSkus,
  createSku,
  updateSku,
  listAdminPlans,
  createPlanVersion,
  updatePlan,
  getPlanFeatures,
  updatePlanFeatures,
  type SkuSummaryDto,
  type ListSkusQuery,
  type CreateSkuBody,
  type UpdateSkuBody,
  type AdminPlanDto,
  type ListAdminPlansQuery,
  type CreatePlanBody,
  type UpdatePlanBody,
  type PlanFeaturesDto,
  type UpdatePlanFeaturesBody,
  provisionQrBatch,
  qrAutoDetachSweep,
  queryAuditEvents,
  queryAuditEventsPage,
  replaceQrCode,
  retireQrCode,
  createClawback,
  initiateOwnershipTransfer,
  approveOwnershipTransfer,
  fulfilPartnerReorder,
  runSettlementBatch,
  type ClawbackBody,
  type ClawbackResultDto,
  type InitiateTransferBody,
  type ApproveTransferBody,
  type TransferInitiatedDto,
  type TransferCompletedDto,
  type SettlementBatchResultDto,
  type ReorderFulfilResultDto,
  type AdminUserDto,
  type AdminUserRoleDto,
  type GrantableUserRole,
  type AdminOrderSummary,
  type AdminOrderDetail,
  type AdminOrderFulfillment,
  type AdminOrderStatus,
  type AdminOrderKind,
  type AdminPaymentOutcome,
  type ListAdminOrdersQuery,
  type AdminOrdersPageResult,
  type AdminPromoDto,
  type AuditAction,
  type AuditEventDto,
  type AuditEventsPageResult,
  type BatchCodeDto,
  type BatchSummaryDto,
  type CreateBatchBody,
  type CreatePromoBody,
  type ListQrBatchCodesQuery,
  type ListQrInventoryQuery,
  type PaginationDto,
  type QrAutoDetachResultDto,
  type QrBatchChannel,
  type QrBatchCodesPageResult,
  type QrBatchStatus,
  type QrCodeStatus,
  type QueryAuditEventsParams,
  type ReplacedDto,
  type RetiredDto,
} from './admin';
export type { Plan, User, Vehicle } from '@autolokate/types';
