export {
  loadActivationPreview,
  loadPartnerActivationPreviewAtEntry,
  loadPurchaseActivationPreviewAtEntry,
  redeemActivationEntitlement,
  seedActivationFromQrPayload,
  seedActivationContext,
  seedPartnerActivationContext,
  rememberActivationContext,
  clearActivationCache,
  clearActivationRedeemAttempt,
  getActivationRevision,
  peekActivationPreview,
  peekActivationCode,
  peekActivationQrCode,
  peekSubscriptionId,
  peekActivationLastError,
  readStoredActivationPreview,
  readStoredActivationQrCode,
  type LoadActivationPreviewResult,
  type RedeemActivationResult,
  type ActivationFlowKind,
} from './activation-service';
export { type ActivationError, type ActivationErrorCode } from './activation-errors';
